swagger: "2.0"
info:
  description: "REST API definitions for Topbot Slack Lambda"
  version: "1.0.0"
  title: "Topbot - Slack Lambda"
host: "localhost:3001"
schemes:
- "http"
paths:
  /approve:
    post:
      tags:
      - "Approve a project"
      summary: "Approve a project"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Project id"
        required: true
        schema:
          type: "object"
          properties:
            projectId:
              type: "string"
              example: "14c83983-58ac-475a-882e-101d47a0e4ec"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        500:
          description: "Internal Server Error"
  /response:
    post:
      tags:
      - "Respond to a project request"
      summary: "Provide response to a project request"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Project id"
        required: true
        schema:
          type: "object"
          properties:
            projectId:
              type: "string"
              example: "14c83983-58ac-475a-882e-101d47a0e4ec"
            text:
              type: "string"
              example: "This is my response"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        500:
          description: "Internal Server Error"
  /slack/events:
    post:
      tags:
      - "Slack events"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      summary: "Endpoint for Slack events. Slack posts command requests to this endpoint. It is meant to be used only through Slack."
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            required: 
            - "challenge"
            properties:
              challenge:
                type: "string"
                example: "983-58ac-475a-882e"
        400:
          description: "Bad request"
  /slack/interactive:
    post:
      tags:
      - "Slack interactive components"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      summary: "Endpoint for Slack interactive components. Interactive elements like button and dialogs post to this endpoint when an action is performed on them"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"